const productsData = [
  {
    id: 1,
    name: "Red Cotton Shirt",
    color: "Red",
    brand: "Zara",
    material: "Cotton",
    category: "Men",
    rating: "4 Stars",
    price: 899,
  },
  {
    id: 2,
    name: "Blue Silk Dress",
    color: "Blue",
    brand: "H&M",
    material: "Silk",
    category: "Women",
    rating: "5 Stars",
    price: 1499,
  },
  {
    id: 3,
    name: "Green Polyester Jacket",
    color: "Green",
    brand: "Nike",
    material: "Polyester",
    category: "Men",
    rating: "3 Stars",
    price: 2199,
  },
  {
    id: 4,
    name: "White Cotton Blend Tee",
    color: "White",
    brand: "Adidas",
    material: "Cotton Blend",
    category: "Kids",
    rating: "4 Stars",
    price: 499,
  },
  {
    id: 5,
    name: "Black Nylon Shorts",
    color: "Black",
    brand: "Puma",
    material: "Nylon",
    category: "Accessories",
    rating: "2 Stars",
    price: 299,
  },
];

export default productsData;
